/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface FavePage {}
  interface FavePageAttributes extends StencilHTMLAttributes {}

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface TrackList {
    'tracks': any;
  }
  interface TrackListAttributes extends StencilHTMLAttributes {
    'onPlaying'?: (event: CustomEvent) => void;
    'tracks'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'FavePage': Components.FavePage;
    'MyApp': Components.MyApp;
    'TrackList': Components.TrackList;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'fave-page': Components.FavePageAttributes;
    'my-app': Components.MyAppAttributes;
    'track-list': Components.TrackListAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLFavePageElement extends Components.FavePage, HTMLStencilElement {}
  var HTMLFavePageElement: {
    prototype: HTMLFavePageElement;
    new (): HTMLFavePageElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLTrackListElement extends Components.TrackList, HTMLStencilElement {}
  var HTMLTrackListElement: {
    prototype: HTMLTrackListElement;
    new (): HTMLTrackListElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'fave-page': HTMLFavePageElement
    'my-app': HTMLMyAppElement
    'track-list': HTMLTrackListElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'fave-page': HTMLFavePageElement;
    'my-app': HTMLMyAppElement;
    'track-list': HTMLTrackListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
