/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface AppHome {

    }

    interface FavePage {

    }

    interface MyApp {

    }

    interface TrackList {
      'tracks': any;
    }
  }


    interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

    var HTMLAppHomeElement: {
      prototype: HTMLAppHomeElement;
      new (): HTMLAppHomeElement;
    };
    

    interface HTMLFavePageElement extends StencilComponents.FavePage, HTMLStencilElement {}

    var HTMLFavePageElement: {
      prototype: HTMLFavePageElement;
      new (): HTMLFavePageElement;
    };
    

    interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

    var HTMLMyAppElement: {
      prototype: HTMLMyAppElement;
      new (): HTMLMyAppElement;
    };
    

    interface HTMLTrackListElement extends StencilComponents.TrackList, HTMLStencilElement {}

    var HTMLTrackListElement: {
      prototype: HTMLTrackListElement;
      new (): HTMLTrackListElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'app-home': JSXElements.AppHomeAttributes;
    'fave-page': JSXElements.FavePageAttributes;
    'my-app': JSXElements.MyAppAttributes;
    'track-list': JSXElements.TrackListAttributes;
    }
  }

  namespace JSXElements {

    export interface AppHomeAttributes extends HTMLAttributes {

    }

    export interface FavePageAttributes extends HTMLAttributes {

    }

    export interface MyAppAttributes extends HTMLAttributes {

    }

    export interface TrackListAttributes extends HTMLAttributes {
      'onPlaying'?: (event: CustomEvent) => void;
      'tracks'?: any;
    }
  }

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'fave-page': HTMLFavePageElement
    'my-app': HTMLMyAppElement
    'track-list': HTMLTrackListElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'fave-page': HTMLFavePageElement;
    'my-app': HTMLMyAppElement;
    'track-list': HTMLTrackListElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

